### ISSUE TITLE
Enhancement: ditch the shadow in the header

### ISSUE THREAD

**Issue by ghost** [canonical/ubuntu-desktop-installer#100]
![image](https://user-images.githubusercontent.com/84561213/119095080-35bc0d80-b9e8-11eb-94d3-68a8840bfe9f.png)

The transparent top panel feels "off" or something. It looks unfinished. Merging it with the titlebar would give the installer a better look.

**Comment by Feichtmeier** [comment]
I strongly disagree. This big blob of black looks very strange to me.

**Comment by lyrebird-sound-cloning-system** [comment]
Maybe the shadow could be dropped then. The welcome screen, for example, has a bold font for the header and it looks clean:
![Screenshot_20210525_063258](https://user-images.githubusercontent.com/84561213/119474988-147a5a80-bd23-11eb-8905-e63a7c5e8ae7.png)

**Comment by Feichtmeier** [comment]
It is good to have this conversation independent of the software stack/technology, but 
1) the screen you've shown is gtk only and 2) the installer is in flutter, which draws intself into a gtk window, resulting in the headerbar being gtk and the window flutter.
The mixed theme is under constant discussion on the gtk side, so instead of replicating this look with force, I would suggest to keep it like this for now.

So in the installer the "top" part is an overriden/inverted part of gtk inside a light theme, which's sense is as I said to be discussed. For more information look here  https://github.com/ubuntu/yaru/discussions/2677

The shadow you see comes from the AppBar inside flutter. So we are mixing up many things here.
alternatively, we could instead use yaru.darkTheme for the installer - mixing up the themes is really not recommended.

**Comment by jpnurmi** [comment]
Without taking a stance on the UI design... Technically, it's possible to have a custom GtkHeaderBar for a Flutter window and communicate with Flutter over a method channel.

**Comment by Feichtmeier** [comment]
Would be great, but then I would stick to light / dark theme standard. We dropped the mixed theme in the flutter theme. Mixed themes do not make sense from a technical and design perspective.
This issue is about a light theme with a dark headerbar and a dark appbar beneath. What is the benefit? It looks unbalanced and does not follow the light / dark standard

**Comment by lyrebird-sound-cloning-system** [comment]
> It is good to have this conversation independent of the software stack/technology, but
> 
>     1. the screen you've shown is gtk only and
> 
>     2. the installer is in flutter, which draws intself into a gtk window, resulting in the headerbar being gtk and the window flutter.
>        The mixed theme is under constant discussion on the gtk side, so instead of replicating this look with force, I would suggest to keep it like this for now.
> 

It was just to demonstrate the header design ("Help improve Ubuntu").

**Comment by Feichtmeier** [comment]
> > ```
> > 1. the screen you've shown is gtk only and
> > ```
> 
> > ```
> > 2. the installer is in flutter, which draws intself into a gtk window, resulting in the headerbar being gtk and the window flutter.
> >    The mixed theme is under constant discussion on the gtk side, so instead of replicating this look with force, I would suggest to keep it like this for now.
> > ```
> 
> It was just to demonstrate the header design ("Help improve Ubuntu").

The shadow comes from the AppBar (https://api.flutter.dev/flutter/material/AppBar-class.html)
and is bound to the Material UI that is used in the yaru theme. 
We decided to follow Google on how the UI looks and thus yaru.dart is a Material theme, only changing the color of the elements , not the form factor or stuff like shadows to ensure plattform independant apps using yaru.dart. So people using material widgets can just switch to yaru.dart without the need to change their widget tree

**Comment by jpnurmi** [comment]
AppBar's elevation was reduced to 1.0 in https://github.com/ubuntu/yaru.dart/pull/73.
