### ISSUE TITLE
ISO Image missing files

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1177]
Hey!

Todays 20221008 ISO is missing the Installer and Firefox and some other files, seems to be a half build

**Comment by bittin** [comment]
Still broken with the 20221010 ISO

**Comment by jpnurmi** [comment]
The Firefox and Installer snaps appear after a long delay because of https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1990884 which has been in https://github.com/snapcore/snapd/pull/12201 which didn't find its way on the stable channel yet. Nevertheless, this is not a bug in the Desktop Installer GUI. :)
