### ISSUE TITLE
Is the linting too aggressive?

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#125]
It feels like those 200 warnings will eventually never be fixed - so is it really needed to include this warning mechanism?

![grafik](https://user-images.githubusercontent.com/15329494/124322986-c1e15900-db80-11eb-8377-b3334aaa6547.png)

CC @oSoMoN @MarcusTomlinson

**Comment by oSoMoN** [comment]
They are `info`-level messages, not warnings, so they won't fail the analyzer.

In general, documenting all public members is a good practice and we're not doing a very good job of it, so having these messages as a reminder is not such a bad thing, even though I agree that this makes the rest of messages less visible.

There are situations where it's legitimate not to document public members, but in those cases we can use annotations in the source code to silence the corresponding messages.

I'm not closing the issue because I'm open to hearing other opinions, but I'm not really in favour of silencing unconditionally all these `public_member_api_docs` messages.

**Comment by Feichtmeier** [comment]
i understand the importance of the documentation. It's just very hard to spot currently important warnings like missing "const" keywords and so on. I mostly try to remember the number of warnings and see if the number changes, then look it up and find warnings I have produced :) 
Maybe we should just start to document the public members then to get a clean workspace :) I could start with the ChooseYourLookPage

**Comment by oSoMoN** [comment]
That sounds like a good initiative!

**Comment by Feichtmeier** [comment]
> That sounds like a good initiative!

Okay, changing this already for new PR, and with https://github.com/canonical/ubuntu-desktop-installer/pull/140 I think we can close this - thanks for the discussion!
