### ISSUE TITLE
Proposal: reduce AppBar elevation for all WizardPages to 1

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#128]
Idea by @muqtxdir 

The AppBar looks kind of too prominent for a desktop app and also different to the design slides.
Muq's idea was to reduce the shadow for the AppBar in all WizardPages, which is doable with setting `elevation: 1`

![1_light](https://user-images.githubusercontent.com/15329494/124362762-4098cd80-dc37-11eb-887b-5c0cc85bbe10.png)
![1_dark](https://user-images.githubusercontent.com/15329494/124362763-41316400-dc37-11eb-9db2-5aa4bdd9442f.png)

WDYT @long-chung @jpnurmi @oSoMoN  ?

**Comment by jpnurmi** [comment]
Not bad! On a related note, looking at these pictures.. isn't the option card's elevation the wrong way around? A button toggled down should be elevated less, right? :slightly_smiling_face:

**Comment by Feichtmeier** [comment]
I was thinking also about the option card. I think it would be better to change the border or the background to a translucent accent colour on selection instead of changing the elevation. Or? Wdyt?

**Comment by jpnurmi** [comment]
Agreed, it would make it easier to spot the selection at a glance.

**Comment by long-chung** [comment]
I really like the border colour on the selected state.
Also is the background grey in the light theme? if it is then it should be reverted back to white to be consistent with the rest of the installer pages.
As a side note, cards should only have elevation on hover. Rested state is just a border.

But otherwise looking really really nice. Thanks.
