### ISSUE TITLE
Include some BASIC information!

### ISSUE THREAD

**Issue by rekcus2** [canonical/ubuntu-desktop-installer#129]
I was able to find out that it is based on some Ubuntu server installer. And build with Flutter, but that is it.

Articles suggest people can try it out in 21.10. Is this true? Is there a compiled version shipped with the daily build? Can I try this with 21.04? What is the difference between "run" and "live run" the readme on how to run it is incomplete and confusing.

I have seen some things that suggest the fucked up manual partitioning has finally been fixed with options disk space to be free for other partitions or something like that. I just tried installing Kubuntu and the installer got ever worse. I had issues for years with the "partion for encrytion" or whatever that option is called. It's not working AT ALL. Going back gives an error about not being able to tot create keyfile or something. I have bad memories of this thing for years as it always had issues. But at least after retries, I was able to manually install a more sane installation without the LVM and swap ...

Also curious about, will it be able to deal with the completely outdated install structure for full disk encryption? Why is Ubuntu still creating a separate /boot partition that is NOT encrypted? I currently have SUSE installed and Grub is able to decrypt the partition it boots from, for years now. And the installer simply creates a SINGLE partition fully encrypted, the way it should be! Ubuntu not only creates a stupid unencrypted boot and has no option for free space and manual was always a pain if it even works at all, it also creates a stupid LVM and swap partition. First nobody with a desktop PC or a good laptop with 16 or 32 gigs of ram even needs swap. Also there is swap files that are not slower for many years also and much simpler. Apparently, everyone says that LVM is great for resizing. Funny thing is I just tried to resize with KDE partition tool and Gparted and they both are NOT able to resize the LVM BS Ubuntu created. Yet I know I used one GUI tool to dead simple resize an ext4 inside LUKS created with a manual installation.

I hope this installer brings a more modern install structure to Ubuntu, at least manually in a non-annoying easy way.

Also what about LUKS 2? Will it use LUKS 2 by default? I read about Grub being able to handle it now. So the installation should simply create a single partition in a single LUKS container and optionally create a swap FILE. And of course you should simply enter the size you want your Ubuntu install to take on the disk and the installer should simply leave empty space in the disk for you to partition to your liking. It's really mind-boggling how horrible the Ubuntu installer is. I really like (K)ubuntu and want to move back to it, but my test install on an HDD already made me angry.

This server installer can I use it to install a Desktop system?

**Comment by oSoMoN** [comment]
You're raising a number of different issues with the current installer, all intertwined, which makes it hard to answer thoroughly.

If you look at [the issues page](https://github.com/canonical/ubuntu-desktop-installer/issues) for the project, you will see that there are bugs filed for specific partitioning requirements, so I suggest you check whether your issues are already known, and if not please file separate bugs for each issue.

Also, please watch your language, this project is subject to the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct) which promotes respect. Offensive words won't help your point, if anything they will turn away contributors who might otherwise be interested in solving your issues.

The project is currently a work in progress, and as such not ready for general testing. The readme instructions are more geared towards developers and contributors. If you feel adventurous you can install the `ubuntu-desktop-installer` classic snap from the edge channel in a virtual machine, (constructive) feedback welcome!
