### ISSUE TITLE
The "hand" cursor doesn't give a truly native look and feel

### ISSUE THREAD

**Issue by martinszeltins** [canonical/ubuntu-desktop-installer#1532]
It seems that when you hover over buttons and menus in the new installer it shows a typical web "hand" cursor. This misses the mark of a truly native experience because nowhere else in the Desktop is there such behavior. When you hover over buttons it should use the "default" cursor icon so it would be consistent with the rest of the desktop experience.

![image](https://user-images.githubusercontent.com/34019878/222916893-58ce2860-45c9-4363-9473-17ce18f5436a.png)

https://ubuntu.com/blog/flutter-and-ubuntu-so-far

> Given that Canonical is going to be making applications for Ubuntu you can count on us putting work into making sure Flutter apps ‘look right’ in the Desktop.  Flutter even allows developers to use web styles that can ‘mimic’ the UI of the system. So a Flutter app built for Ubuntu can use a collection of widgets modelled purposefully after native Ubuntu desktop designs.

**Comment by jpnurmi** [comment]
Agreed :)

- https://github.com/ubuntu/yaru.dart/issues/85
- https://github.com/flutter/flutter/issues/88371

**Comment by elioqoshi** [comment]
@martinszeltins Definitely right, thanks so much for spotting this!

**Comment by jpnurmi** [comment]
Let me re-open this as a reminder because there are still a couple of places where Flutter didn't allow us to customize the mouse cursor.

1. Expandable WiFi device tiles

[Screencast from 2023-03-17 09-21-17.webm](https://user-images.githubusercontent.com/140617/225851139-9941ebef-8fb1-4faa-9b4c-ca4d7147b322.webm)

2. Manual partitioning table

[Screencast from 2023-03-17 09-24-05.webm](https://user-images.githubusercontent.com/140617/225851687-1e42e9cb-085b-4d32-8235-ac2b3e684a30.webm)

**Comment by elioqoshi** [comment]
@jpnurmi Will the next minor release be available by the time we release 23.04?

**Comment by jpnurmi** [comment]
I don't have any insider info but my guess would be no, probably not until the summer. This is pure speculation but I have a feeling they might want to finish multi-window support and it might even turn out to be a major release: Flutter 4 + Dart 3.

But... I could think of some ways to hijack the mouse cursor in those problematic areas as a temporary workaround.
