### ISSUE TITLE
Locale not being set on target system

### ISSUE THREAD

**Issue by dbungert** [canonical/ubuntu-desktop-installer#175]
It looks like cloud-init wants locale in the following format
language_COUNTRY.UTF-8

Please change from the current, which only sends language as a 2 letter code, with no _COUNTRY after it.

**Comment by oSoMoN** [comment]
The current implementation calls `SubiquityClient.setLocale()` when leaving the welcome page, which offers a list of languages.
At this point we are missing information (a country code).
So we need to wait until https://github.com/canonical/ubuntu-desktop-installer/issues/38 is implemented, and only when the user has selected a location can we build a complete locale with language code + country code, and call `setLocale()`.

**Comment by seb128** [comment]
I'm unsure how that's supposed to work? A french person living in Berlin is going to select french as language and Germany on the location selector but it doesn't mean the resulting locale should be fr_DE.UTF-8. Unless we have a list of language that have a country code and only apply the combo when the country selected is valid for the locale?

What is subiquity doing in that regard? One alternative would be to have the welcome list include the variants, which it seems the GNOME initial setup is doing.

Until we figure the details out a workaround could be to set language_LANGUAGE.UTF-8 which would work in some cases at least.

**Comment by dbungert** [comment]
> What is subiquity doing in that regard? 

Subiquity has a list of languages, except for English(UK) - https://raw.githubusercontent.com/canonical/subiquity/c284ff140e40c26f2a4fbd40debad90528eeab03/languagelist

**Comment by oSoMoN** [comment]
That's a very limited subset of possible locales, we should aim at allowing a larger choice.

We could indeed associate a full locale code (language + region) to each language on the welcome page, as a default option. 
Then on the "where are you" page build a locale code with (language + newly selected region), and set it if it happens to be a valid locale.

**Comment by oSoMoN** [comment]
ubiquity seems to be doing basically what I'm suggesting: use the country set on the "where are you" page to [try and build a valid locale code](https://git.launchpad.net/ubiquity/tree/scripts/tzsetup#n29).

`/usr/share/i18n/SUPPORTED` has a list of valid locales to check against.

**Comment by seb128** [comment]
@oSoMoN +1 from me on doing what you suggested and ubiquity is doing

**Comment by mwhudson** [comment]
So let me see if this very l10n naive English speaker (sorry) can get this right. Please correct any terminology I get wrong -- I really do want to know more about this.

1. The very first screen shown is a list of languages.
2. Selecting a language switches the UI to that language (using other localization stuff from the default territory for that language, so selecting french gets you fr_FR not fr_CA -- but subiquity doesn't really have to care about this bit, gettext and friends handle it?). Some of the "language" choices are also location choices too -- Chinese and Portuguese for two, are there others?
3. Then when a location is confirmed, if language + _ + country code is a supported locale, it is the locale that should be set in the target system. If language + _ + country code is not supported, then ... we just set the locale to the language?
4. The language pack for the chosen language should be installed, if it is available (this will be a noop in the case where there is a squashfs with the language pack installed already)
5. at no point in any of this do we even admit that a non-UTF-8 codeset is a thing

Does this sound about right?

**Comment by oSoMoN** [comment]
That sounds basically correct to me (I'm no l10n expert either). A few precisions:

 2. Some of the language choices are variations/dialects (e.g. Brazilian Portuguese). They are often associated with a specific region/country (Brazil in the case of Brazilian Portuguese), but there's no 1-1 mapping (e.g. Traditional Chinese vs Simplified Chinese)

 3. If language + _ + country code is not supported, then nothing should happen, assuming the locale had initially been set in the welcome screen to (language + default region). As an example, I am French and I live in Spain. In the welcome screen the locale would have been set to `fr_FR.UTF-8`, and after selecting my location in Spain, the installer determines that `fr_ES.UTF-8` isn't a valid locale, so it doesn't attempt to change it. If on the other hand I selected a location in Canada, the locale would be updated to `fr_CA.UTF-8`.

 5. I think it is safe to discard any non-UTF8 codeset, but I'm wondering about subiquity's [languagelist](https://raw.githubusercontent.com/canonical/subiquity/c284ff140e40c26f2a4fbd40debad90528eeab03/languagelist) that contains 4 entries without a codeset. Is this intentional?
