### ISSUE TITLE
Installation of Ubuntu Desktop 23.10 fails on Apple hardware

### ISSUE THREAD

**Issue by ogayot** [canonical/ubuntu-desktop-installer#2402]
I can't mark ubuntu-desktop-installer as affected anymore on launchpad so filing a bug here so I can add a watch.

https://bugs.launchpad.net/subiquity/+bug/2040190

TL;DR a workaround was merged in subiquity's ubuntu/mantic branch. Users could benefit from a snap refresh if a new revision gets published to the right channel.

**Comment by vanvugt** [comment]
Thanks for the update. Yes I changed [the Launchpad project](https://bugs.launchpad.net/ubuntu-desktop-installer) to point here for bugs. Because:
* It's the only way to include a Github issue number in the Launchpad task (as [you have](https://launchpad.net/bugs/2040190)); and
* It's more correct to show the project is not maintained in Launchpad. We don't want two separate bug lists growing forever, but you can still create ubuntu-desktop-installer tasks in Launchpad bugs.

**Comment by d-loose** [comment]
@ogayot I've opened https://github.com/canonical/ubuntu-desktop-provision/pull/218 to get those bug fixes into the installer. Shall we merge it and build a new candidate snap for the installer?

**Comment by ogayot** [comment]
@d-loose yes, thanks for the reminder!

**Comment by ogayot** [comment]
This is fixed in version 0+git.4edfab2b currently present in the stable/ubuntu-23.10 channel
