### ISSUE TITLE
Ubuntu Desktop 23.10.1 Installer crashes reliably

### ISSUE THREAD

**Issue by lu4p** [canonical/ubuntu-desktop-installer#2405]
I've reported a bug in launchpad. I haven't heard back from anyone working on the desktop installer yet, so I'm also posting this here in hopes of reaching the right people.

See the linked launchpad issue: https://bugs.launchpad.net/ubuntu-desktop-installer/+bug/2044612

**Comment by seb128** [comment]
The session is closing, from the journal log there is not indication that the installer is hitting a problem but the kernel has errors from the video driver and a reset of the GPU before the session close so it seems more likely a kernel/video driver problem, we will use the launchpad report instead of this one so we can reassign if needed
