### ISSUE TITLE
Screen 5 - Connect to Internet

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#30]
The design for screen n°5, Connect to Internet

![internet](https://people.canonical.com/~platform/desktop/installer/5.%20Connect%20to%20Internet/preview/ubuntu-flutter-installer---material-icons-connect-to-internet---drivers-installed---wi-fi-selected---multi-adapter---expanded.png)

Design details https://people.canonical.com/~platform/desktop/installer/5.%20Connect%20to%20Internet/

**Comment by fitojb** [comment]
The density of the network list could be improved (well, the Yaru theme should be a lot denser than it is). I don’t think it’s terribly useful to display only one and a half items at any time inside that scrollable box.

**Comment by Mannshoch** [comment]
My W-Lan Passkey is way too long to enter it with Keyboard. I like the QR-code solution like I use also on my Mobil phone.
![grafik](https://user-images.githubusercontent.com/7795891/111597517-86d43900-87ce-11eb-9e21-51640b93c673.png)

**Comment by elbeicktalat** [comment]
@Mannshoch 
Hi bro,
it will be so helpful, but how you can scan the QR code?

**Comment by Mannshoch** [comment]
On my laptop I have a Webcam included. On my desktop I attached an USB Webcam. (I use it in Homeoffice)

May you wish a creativ solution: https://randomblog.hu/using-your-android-phone-as-a-webcam-for-ubuntu-20-04-with-droidcam/
And if you wish a strange solution: Use KDEconnect and aus a Mobilephone cam. (but you need a kdeconnect on phone and also pair with it)

**Comment by jpnurmi** [comment]
Hi, feel free to assign this to me if nobody is working on it yet.

**Comment by jpnurmi** [comment]
Since the available vertical space for the Wi-Fi network list is limited, would it be a completely crazy idea to make the whole page scrollable, and expand the current connection type selection like this?

![connect-to-internet](https://user-images.githubusercontent.com/140617/114602105-85474500-9c96-11eb-9e44-a9e435a9b581.gif)

**Comment by Feichtmeier** [comment]
I have the feeling that the whole UI is somehow crowded on the left side of the screen.
I thought about maybe using rather a Tabbed UI here instead of the radio button selection expanding those panels
@jpnurmi

**Comment by MarcusTomlinson** [comment]
> Since the available vertical space for the Wi-Fi network list is limited, would it be a completely crazy idea to make the whole page scrollable, and expand the current connection type selection like this?
> 
> ![connect-to-internet](https://user-images.githubusercontent.com/140617/114602105-85474500-9c96-11eb-9e44-a9e435a9b581.gif)

@long-chung any thoughts?

**Comment by Feichtmeier** [comment]
Fast flutter dummy app to make a point:

https://user-images.githubusercontent.com/15329494/114606530-ab231880-9c9b-11eb-82f1-1df87c8da683.mp4

@MarcusTomlinson @jpnurmi

**Comment by Mannshoch** [comment]
I would propose to add a hint about the speed of a Network (2.4G or 5G) 

(If possible I would prefer If the system could make a little speed test and present this result.)

**Comment by ArishSultan** [comment]
Shouldn't the 'Connect to hidden wifi network' (3rd option) be inside the 'Connect to wifi' option (2nd option)? since both the options have the same context.

And as the user enters the SSID then what changes will happen in UI (how will the user enter the password and which adapter should be used to connect to the hidden wifi), an optimal solution is to use a dialog for taking the password input, after a connection is established we will have to show the connect wifi in the list of one of the adapters. I think it would be redundant to separate these options.

The design proposed by @Feichtmeier does not seem consistent with other screens since there is no screen with a tab view. though it might appear cleaner but isn't consistency important?

The design proposed by @jpnurmi adds scroll ability to the page, but notice that the content is clipped on the bottom just above the two buttons which looks a bit odd.

What is suggested is that instead of using an expansion tile for each adapter and having a separate option for hidden wifi, why not we 2nd option into three sub-parts.
1)- A `DropdownButton` to select adapters, If there is a single adapter then the `Text` widget will be used.
2)- A list of available wifi-networks (w.r.t. the adapter selected from the dropdown above), this list must be of fixed height so, we will not have to worry about the scrolling and clipping.
3)- A button that says 'Connect to a hidden network'. which will open a `Dialog` to take the SSID and password of the hidden wifi network. and this we would have selected an adapter already, so confusion about adapters as I have mentioned in the 2nd paragraph.

I hope you all will understand the concept or else I can provide a sample app with the solution.

**Comment by long-chung** [comment]
> @long-chung any thoughts?

I like this solution. It only shows the extra form elements once you've checked a radio. 
The only thing I would say is to keep the height of the network dropdown a consistent height. Though it would be nice to scan all networks available to you, the chances are that the one you actually want to connect to will be nearest to the top of the list

**Comment by jpnurmi** [comment]
Hi all. I was trying to avoid deviating too much from the proposed design, but if we're still exploring design ideas, here's one. :sunglasses:

![connect-to-internet-dialog](https://user-images.githubusercontent.com/140617/114919896-1f3ef700-9e29-11eb-9663-2fdb4be427b7.gif)

**Comment by seb128** [comment]
The design has been refreshed now which address some of the issues discussed, the screenshot and resources are updated

**Comment by jpnurmi** [comment]
Short summary of a discussion with @long-chung:
- the page is not skipped even when already online
- the active/primary connection is pre-selected when entering the page
- ethernet is selectable only when there's an active ethernet connection
- when ethernet is selected, the button says "continue"
