### ISSUE TITLE
subiquity server fails to start in local dev environment

### ISSUE THREAD

**Issue by oSoMoN** [canonical/ubuntu-desktop-installer#364]
This is a regression caused by https://github.com/canonical/ubuntu-desktop-installer/commit/5c5a97c2d00464133adc0beab6e2f041f5b562c3.

When I try to run the installer app locally, subiquity runs with python3 from the flutter snap:
  
    Traceback (most recent call last):
      File "/snap/flutter/current/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/snap/flutter/current/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/osomon/build/installer/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/cmd/server.py", line 122, in <module>
        sys.exit(main())
      File "/home/osomon/build/installer/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/cmd/server.py", line 78, in main
        from subiquity.server.server import SubiquityServer
      File "/home/osomon/build/installer/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/server/server.py", line 24, in <module>
        from aiohttp import web
    ModuleNotFoundError: No module named 'aiohttp'

More specifically, the change that caused this regression is:

```diff
     _serverProcess = await Process.start(
-      '/usr/bin/python3',
+      'python3',
       subiquityCmd,
```

**Comment by didrocks** [comment]
As said online, we want to have the snap not dependent on system libs, this is why we changed it to point to the one is the SNAP.
there were many issues in the way this is currently implemented (hardcoding system python)                                       
-> this is first using the system libs, and you can have a mismatch between python 3.8 and 3.9, where not all python packages are
(basically, we got the opposite issue in WSL -> no aiohttp because it was in the snap, but not installed on the system)          
-> and you have a dangling python3 symlink in $SNAP/bin, which we removed                                                        
and so, it should use $SNAP/usr/bin, which is a symlink to $SNAP/usr/bin/python3.9, which points to the correct version          

This is working on WSL, is that different on the desktop, or only in dev environment ? (WSL env and tests are passing, and run with the local python3 in the SNAP)

**Comment by jpnurmi** [comment]
> is that different on the desktop, or only in dev environment ?

As far as I can tell, the issue is specific to running the desktop installer with flutter-snap in dev environment. There's `python3(.6)` in `/snap/flutter/current/usr/bin`, and when running with flutter-snap,`/snap/flutter/current/bin` gets prepended to `PATH`.

**Comment by jpnurmi** [comment]
When you build ubuntu-desktop-installer snap, there's `python3(.8)` and `python3-aiohttp` in the snap.

**Comment by didrocks** [comment]
I guess you need to define one which version. Is it a version of dev environment has the flutter PATH before the local one? Should it have the python3 -> python3.8 with correct PYTHONPATH from the local version instead of the flutter snap one?

**Comment by jpnurmi** [comment]
### Flutter vanilla in development environment (OK)
- If I install Flutter from flutter.dev and run `flutter run` with that, Flutter doesn't touch `PATH` so ubuntu-desktop-installer runs whatever `python3` is in my system
- The appropriate dependencies e.g. aiohttp have been installed by the `installdeps.sh` script in subiquity

### Flutter snap in development environment (NOT OK)
- If I install Flutter from snapcraft.io and run `flutter run` with that, `/snap/flutter/current/usr/bin` comes first in `PATH` and there's `python3`
- The Flutter snap has Python 3.6 but no aiohttp

### App snap in production (OK)
- The ubuntu-desktop-installer snap contains `/usr/bin/python3`
- The app snap has Python 3.8 + aiohttp

**Comment by jpnurmi** [comment]
One possible solution would be to add `SubiquityServer._pythonCommand` (on the side of the already existing _pythonModule) and define it as `python3` for WSL and keep it `/usr/bin/python3` for the desktop installer.

**Comment by didrocks** [comment]
It sounds to me that the desktop installer vs WSL is the wrong split. Isn’t the split rather the one you did above?
* dev with flutter dev environment
* dev with flutter snap dev environment
* production

As 1 and 3 are working, I would suggest that we try fixing the flutter snap which sounds wrong to override $PATH with everything it has in it, rather than making the code aware where to look for python binary, wdyt?
For instance, what the flutter snap ships `/snap/flutter/current/usr/bin/locale`, which can make the whole testing, if subiquity uses `locale` wrong, as it’s the not the version and release that will be shipped in finale snap.

**Comment by jpnurmi** [comment]
Sounds good if it's possible to fix this in the flutter snap instead.
