### ISSUE TITLE
Screen 13 - Where Are You

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#38]
The design for screen n°13, Where Are You

![where](https://user-images.githubusercontent.com/10974330/110314520-3d366200-8008-11eb-8d78-63a65d1bceba.png)

Design details https://people.canonical.com/~platform/desktop/installer/13.%20Where%20Are%20You/

**Comment by BillDietrich** [comment]
I am an English-speaking US citizen living in Spain.  So "where I am" is not the same as "how I want to see information".  Maybe the installer could handle this more clearly.  "Where I am" could set initial values, but then have a way to override language, date/time format, currency.

**Comment by madsrh** [comment]
This maps has been used since 8.04 and could IMHO really used a visual update to a more modern look. Just changing the colors would be great. Any change that design would have time to look at this?

I would do it myself, but from the ubiquity package I can see that the map is a PNG, so not easily editable.
https://git.launchpad.net/ubuntu/+source/ubiquity/tree/pixmaps/timezone

**Comment by madsrh** [comment]
@oSoMoN / @ long-chung would you consider rethink this screen? Perhaps just a simple search field with autosearching each typed letter and displaying the results in a popup with the flag of the country 🇬🇧  

Or is the plan is to reimplement the design from ubiquity? If so, here's some feedback from team Yaru:

- The colors look very outdated (and aren't taken from the Yaru color palette)
- The current map png is only 400 x 800px (looks blurry on hi-res screens)
- The pin icon is skeuomorphism and should use the pin icon from the Yaru icon set
- For accessibility we need to provide a high-contrast map for visually impaired
- The pointer often doesn't pick the correct location when clicked

I believe that @muqtxdir is already working on a updated version of the map that fixes a couple of the points mentioned above.

**Comment by long-chung** [comment]
@madsrh Totally agree. The map is outdated but was never in scope to redesign. If there is another option being worked on by another team i'm more than happy to relook at this.

**Comment by Feichtmeier** [comment]
@oSoMoN I'd like to work on this :)

**Comment by Feichtmeier** [comment]
@long-chung @madsrh 

I really like the minimal vibe here, WDYT? padding could be improved I guess

(click to enlarge)
![Peek 2021-07-12 16-07](https://user-images.githubusercontent.com/15329494/125301536-5db25800-e32b-11eb-8ec0-a4cf46192aa2.gif)

**Comment by madsrh** [comment]
It looks cool 😎 but I think it might be confusing for some users. Better add the border so it's clear that it's a textfield

**Comment by oSoMoN** [comment]
I personally think that the map is a valuable element on this screen. A refresh wouldn't hurt, but I would keep it (maybe explore the addition of the search field).

@iainlane pointed out that the current implementation in ubiquity is [a GTK widget](https://launchpad.net/timezonemap), we'll need an equivalent implementation in flutter anyway (and @kenvandine pointed out that we'll want it to work offline).

**Comment by Feichtmeier** [comment]
@oSoMoN I also thought about the offline part.
Created a 15mb json with all cities of the world mapped to their timezones.
Would this be okay, or a concept totally not working because of the file size of the json? 

A rough prototype of this idea can be tested here: https://github.com/Feichtmeier/ubuntu-desktop-installer/tree/where_are_you_page (totally not ready even for a WIP PR because I am somehow still at the who are you page)

I can try to add the PNG's as layeres or re-create the map with flutter, let's see

**Comment by jpnurmi** [comment]
[flutter_map](https://pub.dev/packages/flutter_map) seems to have support for offline maps using [TileMill](https://tilemill-project.github.io/tilemill/).

**Comment by Feichtmeier** [comment]
Sorry due to some IRL trouble (nothing bad, still stressfull) I can't currently work on this. Please unassign me @oSoMoN 
If you are interested in my solution @jpnurmi check out my branch :) Best regards

**Comment by jpnurmi** [comment]
The GTK timezone map widget has [5mb data of cities and countries](https://packages.ubuntu.com/impish/all/libtimezonemap-data/filelist) that originates from [geonames.org](http://www.geonames.org/), and queries for more data from [geoname-lookup.ubuntu.com](https://geoname-lookup.ubuntu.com/?query=london&lang=en&release=impish).

**Comment by jpnurmi** [comment]
@Feichtmeier Thank you for your work on this! I was mostly curious about the options for bundling and fetching the data.

**Comment by mwhudson** [comment]
I was thinking about what the subiquity API for this screen should look like. The basic information the installer needs is the territory part of the locale and timezone. The server should presumably also store the lat/long the user clicks so that it can be displayed if the user goes back to the screen. 

The UI needs lat/long and timezone for its display, but it also needs to be able to map the pixel the user clicks on to a timezone itself. We could do this in the client or the server, presumably using libtimezonemap or something.

So I think the location endpoint should both produce and consume an object that has lat/long/country/timezone properties, and maybe have an api that converts lat/long to country and timezone. Does that sound plausible?

**Comment by jpnurmi** [comment]
We have an interactive map prototype based on:
- [flutter_map](https://pub.dev/packages/flutter_map) (supports offline maps)
- cities15000.txt from libtimezonemap
- http://geoname-lookup.ubuntu.com/

![image](https://user-images.githubusercontent.com/140617/130787575-ee752123-6afa-405a-874f-0387f5a2d22e.png)
