### ISSUE TITLE
Wrong locale set on the installed system

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#397]
Using today's canary image to do a french installation results in a system having /etc/default/locale LANG=fr_FR.UTF-8 and the french langpacks installed but LC_* are set to C.UTF-8

**Comment by seb128** [comment]
Updating the description, when picking netherlands it works so it's probably an issue in the case we use a squashfs rather than installing the language-packs

**Comment by jpnurmi** [comment]
I noticed the same issue when doing a Finnish installation:
- `/etc/default/locale` contains `LANG=fi_FI.UTF-8`
- environment has `LANG=C.UTF-8`
- GDM & GNOME are in English.

The issue occurs at the first boot only. GDM gets the correct language after logout or reboot. It might be a timing issue because in _one_ out of several installations today, GDM & GNOME had Finnish already at the first boot. I suspect `etc/default/locale` gets generated too late i.e. after GDM is already running.

**Comment by jpnurmi** [comment]
I reproduced the issue with Nederlands. GDM was in English at first boot. I switched to console and run `systemctl restart gdm` and then GDM was in Dutch.

**Comment by jpnurmi** [comment]
I recall this was fixed by changing gdm to depend on cloud-init or something similar.
