### ISSUE TITLE
Installation begins before location selection

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#682]
UDI starts installing when pressing the "Start installing" button on the "Write changes to disk" page, whereas Ubiquity starts installing after the "Where are you?" page. Ubiquity is probably right since the correct locale should be set before installing?

**Comment by dbungert** [comment]
Because the install starts with writing an image, we need some info to get that process started (disk, fs format, which image) but not necessarily all the info that is needed for post image steps.
This is nice because we can pipeline the install a bit, and collect information only needed for after imaging once we have started the formatting and imaging steps.

So if it's just an observation that things are different than Ubiquity, I think that's OK.  But if this order is causing a problem, let's figure something out.

**Comment by jpnurmi** [comment]
Yes, you're right. Even if installation starts when partitioning is done, subiquity enters a "post wait" state until identity and timezone have been configured.

1. waiting
2. needs configuration
3. running (after partitioning)
4. post wait (before who/where)
5. post running
6. running
7. done
